### ISSUE TITLE
Kodi crash if a file is missing from a multi rar archive

### ISSUE THREAD

**Issue by Sopor** [xbmc/vfs.rar#49]
If a RAR file is missing from a multi rar archive, Kodi crash instantly when entering the folder.

Windows 10 x64 and Kodi 18.5 x64 (It doesn't crash in Kodi 17.6)

I do have a dmp and a debug log files if needed but it is quite easy to reproduce it by removing one of the rar files. I have tested several times with the same result.

**Comment by Sopor** [comment]
It seems to be the same as #44

**Comment by Sopor** [comment]
If i try to play a DVD that have IFO, and VOB files instead of an ISO it will try to play the VIDEO_TS.IFO but it will get stuck and the only thing that happens it that Kodi freeze.

In Kodi 17.6 it will not try to play it. Instead it will open the RAR file and show its content. It is also possible to play the VIDEO_TS.IFO without Kodi will freeze.

**Comment by AlwinEsch** [comment]
The problem becomes fixed with this https://github.com/xbmc/vfs.rar/pull/50

**Comment by Sopor** [comment]
This is still not fixed. Kodi crash if not all rar files are present in the folder.

**Comment by AlwinEsch** [comment]
This changes also has needed change on Kodi and available currently only on Kodi 19 Matrix, I look about a backport if for others on team OK, then be possible on coming Kodi 18.6 Leia.

**Comment by AlwinEsch** [comment]
Here a backport of this https://github.com/xbmc/vfs.rar/pull/55, shortly after Kodi Leia 18.6 becomes released (has needed a fix for them) comes them in and this should be also fixed on Leia.

**Comment by Sopor** [comment]
I have now installed 18.6 and when i enter a folder with several ZIP, EXE, MP4, 7z, RAR and other types of files Kodi crash. It is my misc download folder. Kodi 17.6 won't crash.

Same thing happens when i enter a folder with missing RAR files.

Maybe i misunderstood something ...

**Comment by AlwinEsch** [comment]
Was needed to wait a bit and needed to merge #55 after the Leia 18.6 is released and available. 
Now is in and new release https://github.com/xbmc/vfs.rar/releases/tag/2.2.0-Leia available.

Should be now available to update in Kodi.

**Comment by Sopor** [comment]
It seem that the crash in my download folder was a password protected RAR file, but after updating to 2.2.0 of vfs i now get in to a loop because it ask me for this password over and over again (it never seems to stop even if i leave the folder, it wasn't easy to leave the folder) so there is still some problems. If should not ask more than one time and there should be an option to disable password protected RAR files so it never tries to automatically open them. The option should make it only ask for password if i'm manually open the archive file.

Do you want me to open a new issue for this?

**Comment by Sopor** [comment]
It seems that if the subs file have more than one subtitle in the rar file it will only auto load one of them. It should load them all.

The subtitle file name is not showing. It will only show a blank line as you can see in this picture:

![image](https://user-images.githubusercontent.com/5789283/75884220-b5ca7780-5e24-11ea-9849-f9978d0fea76.png)

**Comment by AlwinEsch** [comment]
I look to fix asap, can you give me a Link to one of the RAR's or his source (if available and possible) via. Mail to alwinus@kodi.tv.

**Comment by Sopor** [comment]
@AlwinEsch It should be easy to create by your own.
1. Take a video file mkv or mp4.
2. Use WinRAR to create multi-archive files (50 000 000 B or use a lower value if the video files is smaller) in RAR4 and compression STORED and old style volume names.
3. When it is finished, delete one or two of the RAR files.
4. Start Kodi and browse to the folder. It should now crash instantly when you enter the folder.

**Comment by AlwinEsch** [comment]
Has meaned about the subtitles 😄 , the other problem I know and was also easy to reproduce by me.

That’s was also why I brought the update with 2.2.0. And on the opened pull request becomes the password problem prevented and searching still about a playback error.

**Comment by Sopor** [comment]
It seems that the vfs checks for every RAR files in the folder. In Kodi 17.6 (and older) it was still possible to see the video file as long as the first RAR file was in the folder. Now all files need to be there but the real problem is the speed. It takes forever (forever i mean comparing to Kodi 17.6 and older) to open a folder. It is possible to open a multi-archive as long as the first file is there and it should also be possible to play it (not always) but jumping will not work and that is understandable.
There must be another way to do this because this feels like you are going in the wrong direction. Instead of speeding it up, it is now slower to browse folders.

I can't find the subtitle. I need to continue to look for it...

**Comment by AlwinEsch** [comment]
Has released the new version now with 2.2.1 (that it not take to long).

With your, I can reproduce now the subtitle problem and is fixed in 1-2 days and another version becomes released.

With this time problem is a bad thing inside Kodi, there since Kodi 18 it make big file checks, which can by packages a hard work.

Think you mean also on old 2.0.8 it takes to much time (if not a bad packages is there where Kodi bring to crash)? Or specially between 2.0.8 and 2.2.1 a big difference?

**Comment by AlwinEsch** [comment]
About your reported subtitles problem need a change inside Kodi, see https://github.com/xbmc/xbmc/pull/17485 and then available on Leia 18.7

**Comment by Sopor** [comment]
No, 2.2.0 take too much time to open a folder and it won't show the video file if one rar file is missing. In the 17.6 the folder open immediately and if the first rar files is there it will show the video file. Most of the times it is not playable but it will not have this delay as there is now and i think that this delay is there because vfs will check so all the rar files are there before it opens it?

**Comment by Sopor** [comment]
When i updated from 2.2.0 to 2.2.1 the `Download available` didn't go away after i have made the update and when i checked the version of VFS it was still 2.2.0. I was forced to restart Kodi. I have never seen this behavior when i updating an add-on. If a reboot is needed after an update the VFS should bring up some kind of message so i know i need to restart Kodi.

**Comment by AlwinEsch** [comment]
It also happens to me some time ago on another addon, there becomes then in Kodi's update process something wrong and it hangs.

But by binaries is mostly good to make after update a restart, sometimes it works but sometimes not, is related how this is used.
By VFS, AUDIODECODER, AUDIOENCODER, INPUTSTREAM it can work, if it not was started for something before, but is not visible if in use or not.
On PVR is a special handling where it can works better and after update the right version used
On Screensaver/Visualization also OK as they only loaded on work.

That is a part where need really improved, only are to much other things currently, to improve this now. Hope to start soon about them.

Was related to this issue the fault fixed?

**Comment by Sopor** [comment]
Yes, the speed is improved and the size of the video file is also correct and it won't crash Kodi.

The auto load is not working if it is RAR5, but maybe that will only work in Kodi 19, right?

**Comment by AlwinEsch** [comment]
No it should also work by Leia. I'm must look with RAR5 what happens. It was no solid RAR?

**Comment by Sopor** [comment]
I'm now running 2.2.2 of vfs.rar and it is still not auto load if the rar file is STORED and the sub file inside was made with Compression method: BEST. This was a RAR4 archive running Kodi 18.6. It will work if i run it in  Kodi 17.6.

> The auto load is not working if it is RAR5, but maybe that will only work in Kodi 19, right?

I wondering if this was a RAR5 issue? Maybe it was the STORED/BEST issue instead? I couldn't test it in Kodi 17.6 as we know that RAR5 is not supported in Kodi 17.6.

**Comment by Sopor** [comment]
@AlwinEsch I see this several times in the kodi.log. Is this correct?
```
AddOnLog: RAR archive support: CRARControl::GetPassword: invalid data (no/invalid data file found at '/home/osmc/.kodi/userdata/addon_data/vfs.rar//rar-control.xml')
```

**Comment by AlwinEsch** [comment]
@Sopor can you create another issue (if not already one for them present) about the subtitle was not related to the crash of missing file :smile: 

I'm make currently a cleanup of issues to find what still present and what is fixed.

**Comment by Sopor** [comment]
@AlwinEsch You mean about the auto-load issue?

**Comment by AlwinEsch** [comment]
Yes, that I mean, the part of **"Kodi crash if a file is missing from a multi rar archive"** no more present from here.
