### ISSUE TITLE
Video player abruptly stopping when fast-forwarding/seeking while caching is enabled

### ISSUE THREAD

**Issue by sleeve** [xbmc/vfs.rar#59]
I noticed that this add-on was recently updated to 2.2.0 and I verified that it was causing major playback issues on multiple devices for me (Windows and Android TV). The most reproducible bug was that after fast-forwarding/seeking ahead in 10min chunks the video would just stop and kick me back to the movie library. The seeking was also **extremely** slow compared to 2.0.8, but it was able to fast-forward for a few 10min chunks before kicking me back to the library.

I noticed that 2.2.0 "requires" Kodi 18.6 so I upgraded from 18.5 on Windows, ran the same test and the same result is happening. I would also test it on Android TV (Nvidia Shield 2019) but 18.6 hasn't showed up on the Android TV Play Store yet.

Along with this issue I was also experiencing random playback failures (without fast-forwarding) that may be related to this issue. This feels like a huge functionality regression for the "stable" version of Kodi 18. I've had to rollback to 2.0.8 to basically play any video within a rar archive.

Windows 10 (1909) (18363.693)
Kodi 18.5 and 18.6
vfs.rar 2.2.0

Android TV (Nvidia Shield 2019 8.1.1)
Kodi 18.5
vfs.rar 2.2.0

**Comment by AlwinEsch** [comment]
I think you mean that playback stops abruptly, but the Kodi doesn't crash completely and has not to be restarted?

Think to have them fixed on new version.

**Comment by sleeve** [comment]
Correct, crashing may have been the incorrect word to use. I'll update the title.

**Comment by AlwinEsch** [comment]
This then should be fixed on 2.2.1

**Comment by sleeve** [comment]
Yup, appears to be fixed now with 2.2.1. I only tested Kodi 18.6/Windows 10 though. 

Thanks for the fix!

**Comment by sleeve** [comment]
After further testing the issue is still occurring on Android TV (Nvidia Shield 2019) with 2.2.1 (armv7). Windows 10 is working fine though with 2.2.1 (x86_64). 

More info in the related issue comment: https://github.com/xbmc/vfs.rar/issues/60#issuecomment-597779675

**Comment by AlwinEsch** [comment]
I have to ask for security reasons, did you restart Kodi afterwards?
Is a little stupid in Kodi that after an update until the next Kodi start the old one could still run.

Checked on my Amazon FireTV (armv7) with Leia 18.6 and ran normal.

The only thing I urgently need to do is to improve about https://github.com/xbmc/vfs.rar/issues/64, there it takes too long for Seek on password-encrypted packages.

**Comment by sleeve** [comment]
@AlwinEsch I ran some more tests and was able to track down that this issue is being caused by the `<cache>` settings that I'm using within `advancedsettings.xml`. 

```
<cache>
  <memorysize>220200960</memorysize>
  <buffermode>1</buffermode>
  <readfactor>4.0</readfactor>
</cache>
```

This issue was previously only reproducible on my Android TV but it had different cache settings than my Windows 10 system. When I added the cache settings on Windows 10 I was able to reproduce the issue.

Could you try adding those cache settings to your `advancedsettings.xml` and see if you can reproduce it with your test files? I also created a small test video .rar archive that triggers the issue. Please try it and see if you can reproduce the issue with it: https://github.com/sleeve/mkv-rar-test

Thanks for all your help with this!

**Comment by AlwinEsch** [comment]
Thanks that helps, tested now with your example on my Linux and it work. But seen it stops on password protected, maybe thats the same reason, I look further what it does and to fix.

Also I'm look then with it on other OS, maybe performance related, my Linux have a very strong CPU :smile:.

**Comment by sleeve** [comment]
Yeah performance, that also reminds me of something I saw during testing.

When I removed the cache settings from the Nvidia Shield, playback on 2.2.1 was no longer abruptly stopping when seeking but it was taking a very very long time. When pressing the up arrow to seek ahead 10 minutes in a video, it actually took 2 minutes (real-time) before the video skipped 10 minutes and started playing again! That is a serious performance issue compared to 2.0.8 which only took 1 or 2 seconds to seek 10 minutes ahead.

The Nvidia Shield doesn't have the fastest CPU but it has one of the best ones in the small streaming box category. It was also on somewhat slow Wi-Fi trying to stream from another local server.

**Comment by sleeve** [comment]
Ran some more tests on Windows 10 with the **_mkv-rar-test_** video comparing 2.0.8 and 2.2.1 behavior. I wanted to see what the differences were in the log files when seeking with both versions.

**2.0.8 - PASS**
```
2020-03-15 12:21:08.570 T:12024   DEBUG: Keyboard: scancode: 0x48, sym: 0x0111, unicode: 0x0000, modifier: 0x0
2020-03-15 12:21:08.634 T:12024   DEBUG: Previous line repeats 1 times.
2020-03-15 12:21:08.634 T:12024   DEBUG: CInputManager::HandleKey: up (0xf080) pressed, action is ChapterOrBigStepForward
2020-03-15 12:21:08.640 T:8416   DEBUG: CVideoPlayer::SetCaching - caching state 1
2020-03-15 12:21:08.640 T:8416   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
2020-03-15 12:21:08.640 T:8416   DEBUG: demuxer seek to: 6422.000000
2020-03-15 12:21:08.796 T:8416   DEBUG: XFILE::CFileCache::Seek - waiting for position 149524862.
2020-03-15 12:21:08.811 T:11460    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
2020-03-15 12:21:09.031 T:8416   DEBUG: CDVDDemuxFFmpeg::SeekTime - seek ended up on time 6773
2020-03-15 12:21:09.031 T:8416   DEBUG: demuxer seek to: 6422.000000, success
2020-03-15 12:21:09.031 T:8416   DEBUG: CVideoPlayer::FlushBuffers - flushing buffers
2020-03-15 12:21:09.031 T:8416 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2020-03-15 12:21:09.135 T:12024 WARNING: Previous line repeats 1 times.
2020-03-15 12:21:09.135 T:12024   DEBUG: CDVDMsgGeneralSynchronize - global timeout
2020-03-15 12:21:09.135 T:12024   DEBUG: ------ Window Init (DialogSeekBar.xml) ------
2020-03-15 12:21:09.135 T:12024   DEBUG: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------
```

**2.2.1-FAIL**
```
2020-03-15 11:58:25.235 T:6696   DEBUG: Keyboard: scancode: 0x48, sym: 0x0111, unicode: 0x0000, modifier: 0x0
2020-03-15 11:58:25.331 T:6696   DEBUG: Previous line repeats 1 times.
2020-03-15 11:58:25.331 T:6696   DEBUG: CInputManager::HandleKey: up (0xf080) pressed, action is ChapterOrBigStepForward
2020-03-15 11:58:25.334 T:10824   DEBUG: CVideoPlayer::SetCaching - caching state 1
2020-03-15 11:58:25.334 T:10824   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
2020-03-15 11:58:25.334 T:10824   DEBUG: demuxer seek to: 6908.000000
2020-03-15 11:58:25.345 T:12028   DEBUG: AddOnLog: RAR archive support: CRARControl::VolumeChange: Next volume is smb://192.168.1.100/videos/Jellyfish-TEST/rar4x-5MB-store/jellyfish-40-mbps-hd-h264.r25
2020-03-15 11:58:25.355 T:12028   DEBUG: AddOnLog: RAR archive support: CRARControl::VolumeChange: Next volume is smb://192.168.1.100/videos/Jellyfish-TEST/rar4x-5MB-store/jellyfish-40-mbps-hd-h264.r26
2020-03-15 11:58:25.369 T:12028   DEBUG: AddOnLog: RAR archive support: CRARControl::VolumeChange: Next volume is smb://192.168.1.100/videos/Jellyfish-TEST/rar4x-5MB-store/jellyfish-40-mbps-hd-h264.r27
2020-03-15 11:58:25.384 T:12028   DEBUG: AddOnLog: RAR archive support: CRARControl::VolumeChange: Next volume is smb://192.168.1.100/videos/Jellyfish-TEST/rar4x-5MB-store/jellyfish-40-mbps-hd-h264.r28
2020-03-15 11:58:25.386 T:10824   DEBUG: XFILE::CFileCache::Seek - waiting for position 149524862.
2020-03-15 11:58:25.407 T:8592    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
2020-03-15 11:58:25.407 T:8592   ERROR: CFileCache::Process - Error 0 seeking. Seek returned -1
2020-03-15 11:58:25.407 T:8592    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
2020-03-15 11:58:25.407 T:10824   DEBUG: CDVDDemuxFFmpeg::SeekTime - seek ended up on time 7741
2020-03-15 11:58:25.407 T:10824   DEBUG: demuxer seek to: 6908.000000, success
2020-03-15 11:58:25.407 T:10824   DEBUG: CVideoPlayer::FlushBuffers - flushing buffers
2020-03-15 11:58:25.407 T:10824 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2020-03-15 11:58:25.831 T:6696 WARNING: Previous line repeats 1 times.
2020-03-15 11:58:25.831 T:6696   DEBUG: CDVDMsgGeneralSynchronize - global timeout
2020-03-15 11:58:25.834 T:6696   DEBUG: ------ Window Init (DialogSeekBar.xml) ------
2020-03-15 11:58:25.835 T:6696   DEBUG: ------ Window Init (Custom_1109_TopBarOverlay.xml) 
```

The key difference seems to be `ERROR: CFileCache::Process - Error 0 seeking. Seek returned -1`. The 2.0.8 log still has the `INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)` info entry but it never has a the error `Seek returned -1` like 2.2.1 does.

**Comment by AlwinEsch** [comment]
Have added a request about fix https://github.com/xbmc/vfs.rar/pull/65

Not sure if really fixed, but on them much more log calls added to see better what happens.

Also can I close my other issue here https://github.com/xbmc/vfs.rar/issues/64

If you could test with them from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-65/1/artifacts would be nice :smile:.

**Comment by sleeve** [comment]
@AlwinEsch I ran more tests with the above 2.2.2b test build on Windows 10 and Nvidia Shield and both seem to be working now with caching enabled. This issue should be ok to finally close after 2.2.2 is released. I'll continue to test the 2.2.2b to see if any other issues pop up though.

Thanks again for the fix!
